// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeizureTrackerAPI.Context;

#nullable disable

namespace SeizureTrackerAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250730031552_UpdateDB")]
    partial class UpdateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SeizureTrackerAPI.Models.PersonModel", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ChildData")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonID");

                    b.ToTable("PersonModels");
                });

            modelBuilder.Entity("SeizureTrackerAPI.Models.Seizures", b =>
                {
                    b.Property<Guid>("SeizureEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeizureComments")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SeizureDateTime")
                        .HasColumnType("TEXT");

                    b.Property<float>("SeizureDurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<int>("SeizureSeverity")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeizureEventId");

                    b.ToTable("Seizures");
                });
#pragma warning restore 612, 618
        }
    }
}
